import type { Activity } from "@/types";

export const activities: Activity[] = [
  {
    slug: "nusa-penida-snorkel",
    name: "Nusa Penida Snorkeling & Cliff Viewpoints",
    destinationSlug: "bali",
    destinationName: "Bali",
    category: "Island Hopping",
    heroImage: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=1200",
    duration: "Full day (10 hrs)",
    rating: 4.8,
    reviewCount: 1240,
    price: 3499,
    currency: "₹",
    description:
      "A speedboat crossing to Nusa Penida, snorkeling with manta rays at Manta Point, then a stop at the Kelingking and Broken Beach viewpoints.",
    highlights: ["Manta Point snorkeling", "Kelingking Beach viewpoint", "Angel's Billabong", "Lunch included"],
    included: ["Speedboat transfer", "Snorkeling gear", "Lunch", "Licensed guide"],
    difficulty: "Easy",
  },
  {
    slug: "mount-batur-sunrise-trek",
    name: "Mount Batur Sunrise Trek",
    destinationSlug: "bali",
    destinationName: "Bali",
    category: "Mountain Trekking",
    heroImage: "https://images.unsplash.com/photo-1512757776214-77e01b0b4c68?w=1200",
    duration: "6 hrs (overnight pickup)",
    rating: 4.7,
    reviewCount: 980,
    price: 2299,
    currency: "₹",
    description:
      "A pre-dawn hike up an active volcano, reaching the summit in time for sunrise over Mount Agung and Lake Batur, with breakfast cooked in volcanic steam vents.",
    highlights: ["Sunrise summit views", "Volcanic steam-cooked breakfast", "Lake Batur panorama"],
    included: ["Hotel pickup", "Guide", "Breakfast", "Flashlight"],
    difficulty: "Moderate",
  },
  {
    slug: "sahara-style-dune-safari",
    name: "Desert Safari with Dune Bashing",
    destinationSlug: "dubai",
    destinationName: "Dubai",
    category: "Desert Safari",
    heroImage: "https://images.unsplash.com/photo-1451337516015-6b6e9a44a8a3?w=1200",
    duration: "6 hrs (afternoon–evening)",
    rating: 4.8,
    reviewCount: 3210,
    price: 4499,
    currency: "₹",
    description:
      "Dune bashing in a 4x4, a camel-riding stop, sandboarding, and a Bedouin-style camp dinner under the stars with live entertainment.",
    highlights: ["4x4 dune bashing", "Sandboarding", "Camel riding", "BBQ dinner with live shows"],
    included: ["Hotel pickup & drop-off", "BBQ buffet dinner", "Unlimited soft drinks", "Live entertainment"],
    difficulty: "Easy",
  },
  {
    slug: "burj-khalifa-at-the-top",
    name: "Burj Khalifa: At the Top Experience",
    destinationSlug: "dubai",
    destinationName: "Dubai",
    category: "City Tours",
    heroImage: "https://images.unsplash.com/photo-1518684079-3c830dcef090?w=1200",
    duration: "1.5 hrs",
    rating: 4.7,
    reviewCount: 5410,
    price: 2999,
    currency: "₹",
    description:
      "High-speed elevator to the 124th and 125th floor observation decks of the world's tallest building, with views across the entire city.",
    highlights: ["124th & 125th floor decks", "Interactive telescopes", "Sunset time slots available"],
    included: ["Entry ticket", "Audio guide"],
    difficulty: "Easy",
  },
  {
    slug: "matterhorn-glacier-paradise-tour",
    name: "Matterhorn Glacier Paradise Cable Car Tour",
    destinationSlug: "zermatt",
    destinationName: "Zermatt",
    category: "Mountain Trekking",
    heroImage: "https://images.unsplash.com/photo-1531366936337-7c912a4589a7?w=1200",
    duration: "4 hrs",
    rating: 4.9,
    reviewCount: 720,
    price: 6999,
    currency: "₹",
    description:
      "Europe's highest-altitude cable car ride to the Klein Matterhorn viewing platform at 3,883m, with an ice palace and glacier walk.",
    highlights: ["3,883m summit platform", "Glacier ice palace", "Views into Italy"],
    included: ["Cable car tickets", "Ice palace entry", "Guide"],
    difficulty: "Easy",
  },
  {
    slug: "tokyo-ski-and-onsen-day",
    name: "Skiing & Onsen Day Trip from Tokyo",
    destinationSlug: "tokyo",
    destinationName: "Tokyo",
    category: "Skiing",
    heroImage: "https://images.unsplash.com/photo-1551524559-8af4e6624178?w=1200",
    duration: "Full day (12 hrs)",
    rating: 4.6,
    reviewCount: 540,
    price: 5499,
    currency: "₹",
    description:
      "A bullet-train day trip to Gala Yuzawa's ski slopes, followed by a soak in a traditional hot-spring onsen before returning to Tokyo.",
    highlights: ["Beginner-friendly slopes", "Equipment rental included", "Traditional onsen soak"],
    included: ["Round-trip Shinkansen", "Lift pass", "Equipment rental", "Onsen entry"],
    difficulty: "Moderate",
  },
  {
    slug: "tokyo-old-town-cultural-walk",
    name: "Asakusa & Old Tokyo Cultural Walking Tour",
    destinationSlug: "tokyo",
    destinationName: "Tokyo",
    category: "City Tours",
    heroImage: "https://images.unsplash.com/photo-1554797589-7241bb691973?w=1200",
    duration: "3 hrs",
    rating: 4.8,
    reviewCount: 1650,
    price: 1899,
    currency: "₹",
    description:
      "A guided walk through Senso-ji Temple, Nakamise shopping street, and the quiet backstreets of Yanaka, ending with a traditional tea ceremony.",
    highlights: ["Senso-ji Temple", "Nakamise street food", "Tea ceremony"],
    included: ["Local guide", "Tea ceremony", "Snack tastings"],
    difficulty: "Easy",
  },
  {
    slug: "phi-phi-islands-speedboat",
    name: "Phi Phi Islands Speedboat Tour",
    destinationSlug: "phuket",
    destinationName: "Phuket",
    category: "Island Hopping",
    heroImage: "https://images.unsplash.com/photo-1552465011-b4e21bf6e79a?w=1200",
    duration: "Full day (9 hrs)",
    rating: 4.7,
    reviewCount: 2890,
    price: 3299,
    currency: "₹",
    description:
      "A speedboat loop through Maya Bay, Monkey Beach, and Pileh Lagoon, with snorkeling stops and lunch on Phi Phi Don.",
    highlights: ["Maya Bay", "Pileh Lagoon snorkeling", "Monkey Beach", "Buffet lunch"],
    included: ["Speedboat transfer", "Snorkeling gear", "Lunch", "National park fees"],
    difficulty: "Easy",
  },
  {
    slug: "phuket-muay-thai-class",
    name: "Muay Thai Training Session",
    destinationSlug: "phuket",
    destinationName: "Phuket",
    category: "Cultural Tours",
    heroImage: "https://images.unsplash.com/photo-1544919982-b61976f0ba43?w=1200",
    duration: "2 hrs",
    rating: 4.9,
    reviewCount: 410,
    price: 999,
    currency: "₹",
    description:
      "A beginner-friendly Muay Thai session with a former professional fighter, covering stance, pad work, and basic combinations.",
    highlights: ["1-on-1 pad work", "No experience required", "Gloves and wraps provided"],
    included: ["Gloves & hand wraps", "Water", "Certificate of completion"],
    difficulty: "Moderate",
  },
  {
    slug: "singapore-night-safari",
    name: "Singapore Night Safari",
    destinationSlug: "singapore-city",
    destinationName: "Singapore",
    category: "Wildlife Safari",
    heroImage: "https://images.unsplash.com/photo-1549366021-9f761d450615?w=1200",
    duration: "3 hrs (evening)",
    rating: 4.8,
    reviewCount: 2200,
    price: 2199,
    currency: "₹",
    description:
      "The world's first nocturnal wildlife park — a tram ride and walking trails through habitats of leopards, tigers, and flying foxes after dark.",
    highlights: ["Tram safari", "Walking trails", "Fire dance show"],
    included: ["Entry ticket", "Tram ride"],
    difficulty: "Easy",
  },
  {
    slug: "maldives-whale-shark-dive",
    name: "Whale Shark & Manta Ray Diving Expedition",
    destinationSlug: "maldives-atoll",
    destinationName: "Maldives",
    category: "Scuba Diving",
    heroImage: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=1200",
    duration: "Half day (4 hrs)",
    rating: 4.9,
    reviewCount: 610,
    price: 8999,
    currency: "₹",
    description:
      "A boat trip to South Ari Atoll's whale shark corridor, with two dive or snorkel sessions alongside whale sharks and manta rays.",
    highlights: ["Whale shark encounters", "Manta ray cleaning stations", "Certified dive guide"],
    included: ["Boat transfer", "Dive/snorkel equipment", "Marine biologist guide"],
    difficulty: "Moderate",
  },
  {
    slug: "london-thames-royal-tour",
    name: "Royal London Walking Tour",
    destinationSlug: "london",
    destinationName: "London",
    category: "City Tours",
    heroImage: "https://images.unsplash.com/photo-1529655683826-aba9b3e77383?w=1200",
    duration: "2.5 hrs",
    rating: 4.7,
    reviewCount: 1870,
    price: 1499,
    currency: "₹",
    description:
      "A guided walk from Buckingham Palace to Westminster Abbey, timed to catch the Changing of the Guard along the way.",
    highlights: ["Changing of the Guard", "Westminster Abbey exterior", "St. James's Park"],
    included: ["Local guide", "Small group (max 15)"],
    difficulty: "Easy",
  },
  {
    slug: "nyc-statue-of-liberty-cruise",
    name: "Statue of Liberty & Ellis Island Cruise",
    destinationSlug: "new-york-city",
    destinationName: "New York",
    category: "City Tours",
    heroImage: "https://images.unsplash.com/photo-1509644851169-2acc08aa25b5?w=1200",
    duration: "4 hrs",
    rating: 4.7,
    reviewCount: 3980,
    price: 2499,
    currency: "₹",
    description:
      "A ferry to Liberty Island and Ellis Island, with pedestal access to the Statue of Liberty and the Immigration Museum.",
    highlights: ["Statue of Liberty pedestal access", "Ellis Island Immigration Museum", "Manhattan skyline views"],
    included: ["Ferry ticket", "Audio guide", "Museum entry"],
    difficulty: "Easy",
  },
  {
    slug: "jaipur-hot-air-balloon",
    name: "Hot Air Balloon Ride over Jaipur",
    destinationSlug: "jaipur",
    destinationName: "Jaipur, Rajasthan",
    category: "Adventure",
    heroImage: "https://images.unsplash.com/photo-1507608616759-54f48f0af0ee?w=1200",
    duration: "3 hrs (sunrise)",
    rating: 4.8,
    reviewCount: 860,
    price: 8999,
    currency: "₹",
    description:
      "A sunrise balloon flight over the Aravalli hills and Amber Fort, followed by a traditional breakfast on landing.",
    highlights: ["Sunrise flight", "Amber Fort aerial views", "Breakfast on landing"],
    included: ["Hotel pickup", "Flight certificate", "Breakfast"],
    difficulty: "Easy",
  },
  {
    slug: "rishikesh-rafting",
    name: "Ganges Whitewater Rafting (Grade III–IV)",
    destinationSlug: "rishikesh",
    destinationName: "Rishikesh, Uttarakhand",
    category: "Adventure",
    heroImage: "https://images.unsplash.com/photo-1530866495561-507c9faab8d6?w=1200",
    duration: "3 hrs",
    rating: 4.8,
    reviewCount: 1340,
    price: 1299,
    currency: "₹",
    description:
      "A 16km rafting stretch from Shivpuri to Rishikesh through rapids like Roller Coaster and Golf Course, with a cliff-jump stop.",
    highlights: ["16km rapids run", "Cliff jumping stop", "Certified river guides"],
    included: ["Rafting gear", "Life jacket & helmet", "Guide"],
    difficulty: "Challenging",
  },
  {
    slug: "alleppey-houseboat-cruise",
    name: "Backwater Houseboat Day Cruise",
    destinationSlug: "alleppey",
    destinationName: "Alleppey, Kerala",
    category: "Cultural Tours",
    heroImage: "https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?w=1200",
    duration: "6 hrs",
    rating: 4.7,
    reviewCount: 990,
    price: 3999,
    currency: "₹",
    description:
      "A daytime houseboat cruise through narrow backwater canals, coconut groves, and paddy fields, with a Kerala-style lunch on board.",
    highlights: ["Narrow canal cruising", "Village stop", "Kerala thali lunch"],
    included: ["Houseboat cruise", "Lunch", "Guide"],
    difficulty: "Easy",
  },
  {
    slug: "goa-spice-plantation-tour",
    name: "Spice Plantation & Elephant Bathing Tour",
    destinationSlug: "goa",
    destinationName: "Goa",
    category: "Cultural Tours",
    heroImage: "https://images.unsplash.com/photo-1553531384-cc64ac80f931?w=1200",
    duration: "4 hrs",
    rating: 4.5,
    reviewCount: 720,
    price: 1499,
    currency: "₹",
    description:
      "A walking tour through a working spice plantation with tastings, followed by a traditional Goan thali lunch under banana leaves.",
    highlights: ["Spice tasting walk", "Traditional Goan lunch", "Local farming demos"],
    included: ["Guide", "Lunch", "Spice tasting"],
    difficulty: "Easy",
  },
  {
    slug: "manali-paragliding-solang",
    name: "Paragliding over Solang Valley",
    destinationSlug: "manali",
    destinationName: "Manali, Himachal Pradesh",
    category: "Adventure",
    heroImage: "https://images.unsplash.com/photo-1521673461164-de300ebcfb17?w=1200",
    duration: "1.5 hrs",
    rating: 4.7,
    reviewCount: 640,
    price: 1999,
    currency: "₹",
    description:
      "A tandem paragliding flight over Solang Valley with a certified pilot, launching from the ridge above the valley floor.",
    highlights: ["Tandem flight with certified pilot", "Valley & glacier views", "GoPro footage available"],
    included: ["Safety gear", "Certified pilot", "Transfer to launch site"],
    difficulty: "Moderate",
  },
];

export function getAllActivities(): Activity[] {
  return activities;
}

export function getActivityBySlug(slug: string): Activity | undefined {
  return activities.find((a) => a.slug === slug);
}

export function getActivitiesByDestination(destinationSlug: string): Activity[] {
  return activities.filter((a) => a.destinationSlug === destinationSlug);
}

export function getActivityCategories(): string[] {
  return Array.from(new Set(activities.map((a) => a.category)));
}

export function searchActivities(query: string): Activity[] {
  const q = query.trim().toLowerCase();
  if (!q) return activities;
  return activities.filter(
    (a) =>
      a.name.toLowerCase().includes(q) ||
      a.destinationName.toLowerCase().includes(q) ||
      a.category.toLowerCase().includes(q)
  );
}
