import type { Country, GlobeCountry } from "@/types";

export const countries: Country[] = [
  {
    slug: "india",
    name: "India",
    isoCode: "IN",
    heroImage: "https://images.unsplash.com/photo-1524492412937-b28074a5d7da?w=1600",
    description:
      "A subcontinent of deserts, backwaters, snow peaks and coastline — India spans more climates and cultures than most continents, from Rajasthan's forts to Kerala's canals.",
    currency: "Indian Rupee (INR)",
    language: "Hindi, English, and 21 official regional languages",
    timezone: "IST (UTC+5:30)",
    climate: "Tropical monsoon, varies sharply by region",
    bestSeason: "October–March",
    avgBudget: "₹2,500–₹6,000/day",
    visaInfo: "e-Visa available for most nationalities, 30/90/365-day options.",
    localFoods: ["Butter chicken", "Dosa", "Rogan josh", "Pani puri"],
    festivals: ["Diwali", "Holi", "Durga Puja"],
    latitude: 20.5937,
    longitude: 78.9629,
  },
  {
    slug: "indonesia",
    name: "Indonesia",
    isoCode: "ID",
    heroImage: "https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=1600",
    description:
      "17,000 islands of volcanic rice terraces, temple towns, and reef-lined coastlines — Bali is only the beginning of Indonesia's range.",
    currency: "Indonesian Rupiah (IDR)",
    language: "Bahasa Indonesia",
    timezone: "WIB/WITA/WIT (UTC+7 to +9)",
    climate: "Tropical, wet and dry seasons",
    bestSeason: "April–October",
    avgBudget: "$35–$90/day",
    visaInfo: "Visa-on-arrival for most nationalities, 30 days extendable.",
    localFoods: ["Nasi goreng", "Satay", "Rendang", "Gado-gado"],
    festivals: ["Nyepi (Day of Silence)", "Galungan"],
    latitude: -0.7893,
    longitude: 113.9213,
  },
  {
    slug: "france",
    name: "France",
    isoCode: "FR",
    heroImage: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=1600",
    description:
      "From Parisian boulevards to Provençal lavender fields and Alpine peaks, France pairs centuries of art and architecture with some of the world's most celebrated food.",
    currency: "Euro (EUR)",
    language: "French",
    timezone: "CET (UTC+1)",
    climate: "Temperate, four distinct seasons",
    bestSeason: "April–June, September–October",
    avgBudget: "€90–€220/day",
    visaInfo: "Schengen visa required for most non-EU nationalities.",
    localFoods: ["Croissant", "Coq au vin", "Ratatouille", "Crème brûlée"],
    festivals: ["Bastille Day", "Cannes Film Festival"],
    latitude: 46.2276,
    longitude: 2.2137,
  },
  {
    slug: "uae",
    name: "United Arab Emirates",
    isoCode: "AE",
    heroImage: "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=1600",
    description:
      "Skyscrapers rising from the desert, souks beside superyacht marinas — the UAE compresses old Gulf trade routes and hyper-modern ambition into one coastline.",
    currency: "UAE Dirham (AED)",
    language: "Arabic, English widely spoken",
    timezone: "GST (UTC+4)",
    climate: "Desert, hot most of the year",
    bestSeason: "November–March",
    avgBudget: "$120–$300/day",
    visaInfo: "Visa-on-arrival for most nationalities, 30–90 days.",
    localFoods: ["Machboos", "Shawarma", "Luqaimat", "Al Harees"],
    festivals: ["Dubai Shopping Festival", "Eid al-Fitr"],
    latitude: 23.4241,
    longitude: 53.8478,
  },
  {
    slug: "switzerland",
    name: "Switzerland",
    isoCode: "CH",
    heroImage: "https://images.unsplash.com/photo-1531366936337-7c912a4589a7?w=1600",
    description:
      "Glacial lakes, cogwheel trains and Alpine villages — Switzerland is built for slow, scenic travel between mountains that never seem to run out.",
    currency: "Swiss Franc (CHF)",
    language: "German, French, Italian, Romansh",
    timezone: "CET (UTC+1)",
    climate: "Alpine, cold winters, mild summers",
    bestSeason: "June–September, December–March",
    avgBudget: "CHF 180–CHF 400/day",
    visaInfo: "Schengen visa required for most non-EU nationalities.",
    localFoods: ["Fondue", "Raclette", "Rösti", "Swiss chocolate"],
    festivals: ["Fasnacht", "Sechseläuten"],
    latitude: 46.8182,
    longitude: 8.2275,
  },
  {
    slug: "japan",
    name: "Japan",
    isoCode: "JP",
    heroImage: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1600",
    description:
      "Neon megacities and quiet mountain shrines exist a bullet-train ride apart — Japan rewards travelers who move between both.",
    currency: "Japanese Yen (JPY)",
    language: "Japanese",
    timezone: "JST (UTC+9)",
    climate: "Four seasons; cherry blossoms in spring, snow in the north",
    bestSeason: "March–May, October–November",
    avgBudget: "¥12,000–¥30,000/day",
    visaInfo: "Visa-free for many nationalities up to 90 days.",
    localFoods: ["Sushi", "Ramen", "Okonomiyaki", "Wagyu"],
    festivals: ["Cherry Blossom Festival", "Gion Matsuri"],
    latitude: 36.2048,
    longitude: 138.2529,
  },
  {
    slug: "thailand",
    name: "Thailand",
    isoCode: "TH",
    heroImage: "https://images.unsplash.com/photo-1552465011-b4e21bf6e79a?w=1600",
    description:
      "Limestone islands, golden temples, and some of the world's best street food make Thailand a favorite entry point into Southeast Asia.",
    currency: "Thai Baht (THB)",
    language: "Thai",
    timezone: "ICT (UTC+7)",
    climate: "Tropical, hot and humid with a distinct rainy season",
    bestSeason: "November–February",
    avgBudget: "฿1,500–฿4,000/day",
    visaInfo: "Visa exempt for many nationalities up to 30–60 days.",
    localFoods: ["Pad Thai", "Tom Yum", "Green curry", "Mango sticky rice"],
    festivals: ["Songkran", "Loy Krathong"],
    latitude: 15.87,
    longitude: 100.9925,
  },
  {
    slug: "singapore",
    name: "Singapore",
    isoCode: "SG",
    heroImage: "https://images.unsplash.com/photo-1525625293386-3f8f99389edd?w=1600",
    description:
      "A city-state that packs hawker markets, rainforest, and some of the world's most ambitious architecture into a single, hyper-efficient island.",
    currency: "Singapore Dollar (SGD)",
    language: "English, Mandarin, Malay, Tamil",
    timezone: "SGT (UTC+8)",
    climate: "Tropical, warm and humid year-round",
    bestSeason: "February–April",
    avgBudget: "S$120–S$300/day",
    visaInfo: "Visa-free for many nationalities up to 30–90 days.",
    localFoods: ["Chicken rice", "Laksa", "Chilli crab", "Satay"],
    festivals: ["Chinese New Year", "Deepavali"],
    latitude: 1.3521,
    longitude: 103.8198,
  },
  {
    slug: "maldives",
    name: "Maldives",
    isoCode: "MV",
    heroImage: "https://images.unsplash.com/photo-1573843981267-be1999ff37cd?w=1600",
    description:
      "A scatter of coral atolls in the Indian Ocean, built almost entirely around overwater villas, private lagoons, and reef diving.",
    currency: "Maldivian Rufiyaa (MVR)",
    language: "Dhivehi, English widely spoken in resorts",
    timezone: "MVT (UTC+5)",
    climate: "Tropical, warm year-round with a wet season May–October",
    bestSeason: "November–April",
    avgBudget: "$250–$900/day",
    visaInfo: "Visa-on-arrival for all nationalities, 30 days free.",
    localFoods: ["Mas huni", "Garudhiya", "Fihunu mas"],
    festivals: ["Eid al-Fitr", "Independence Day"],
    latitude: 3.2028,
    longitude: 73.2207,
  },
  {
    slug: "united-kingdom",
    name: "United Kingdom",
    isoCode: "GB",
    heroImage: "https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?w=1600",
    description:
      "From London's museums to the Scottish Highlands, the UK compresses castles, coastline, and centuries of history into a compact, well-connected island.",
    currency: "Pound Sterling (GBP)",
    language: "English",
    timezone: "GMT/BST (UTC+0/+1)",
    climate: "Temperate maritime, mild and often rainy",
    bestSeason: "May–September",
    avgBudget: "£100–£250/day",
    visaInfo: "Visa-free for many nationalities up to 6 months.",
    localFoods: ["Fish and chips", "Sunday roast", "Full English breakfast"],
    festivals: ["Notting Hill Carnival", "Edinburgh Fringe"],
    latitude: 55.3781,
    longitude: -3.436,
  },
  {
    slug: "united-states",
    name: "United States",
    isoCode: "US",
    heroImage: "https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?w=1600",
    description:
      "From Manhattan skylines to national parks and coastal highways, the scale of the US means every trip feels like a different country.",
    currency: "US Dollar (USD)",
    language: "English",
    timezone: "Multiple, UTC-5 to UTC-10",
    climate: "Varies widely by region",
    bestSeason: "April–June, September–November",
    avgBudget: "$150–$400/day",
    visaInfo: "ESTA/visa-waiver for many nationalities up to 90 days.",
    localFoods: ["Burgers", "BBQ", "Bagels", "Deep dish pizza"],
    festivals: ["Thanksgiving", "Fourth of July"],
    latitude: 37.0902,
    longitude: -95.7129,
  },
];

export function getAllCountries(): Country[] {
  return countries;
}

export function getCountryBySlug(slug: string): Country | undefined {
  return countries.find((c) => c.slug === slug);
}

export function getGlobeCountries(destinationCounts: Record<string, number>): GlobeCountry[] {
  return countries.map((c) => ({
    slug: c.slug,
    name: c.name,
    isoCode: c.isoCode,
    latitude: c.latitude,
    longitude: c.longitude,
    destinationCount: destinationCounts[c.slug] ?? 0,
    bestSeason: c.bestSeason,
  }));
}
